"use client";
import { BrainPanel } from "@/components/game/BrainPanel";
import { nextMission } from "@/lib/learning/model";
import Link from "@/components/game/AppLink";
import {
  ArrowDown,
  ArrowUpRight,
  Check,
  Code2,
  FlaskConical,
  ShieldCheck,
  Activity,
} from "lucide-react";
import { Header, Footer } from "@/components/game/Chrome";
import { useSession } from "@/components/game/SessionProvider";
import metrics from "@/content/evaluation.json";
import localMetrics from "@/content/local-evaluation.json";
const layers = [
  ["Learner interaction", "Build, explain, correct, transfer"],
  ["Deterministic MathKernel", "Exact rational arithmetic. Authored truth."],
  ["Explanation analysis", "Strict schema. Grounded concepts. Safe fallback."],
  ["Misconception model", "Stable authored codes. Evidence-based confidence."],
  [
    "Mastery + adaptive policy",
    "Raw evidence. Two independent transfer gates.",
  ],
  ["The next discovery", "Target the gap. Change the representation."],
];
export default function Lab() {
  const { session } = useSession(),
    mission = nextMission(session.learning),
    aiEvents = session.events.filter((e) => e.name === "explanation_submitted"),
    fallback = session.events.filter((e) => e.name === "fallback_used").length,
    latency = aiEvents.length
      ? Math.round(
          aiEvents.reduce((a, e) => a + (e.latencyMs ?? 0), 0) /
            aiEvents.length,
        )
      : null;
  return (
    <main className="adult-page lab-page">
      <Header light />
      <div className="adult-container">
        <div className="adult-heading">
          <div>
            <span className="eyebrow">
              GENERATIVE ON THE EDGES. DETERMINISTIC AT THE CORE.
            </span>
            <h1>How Pip learns</h1>
            <p>
              A model can explore the idea. It never gets to decide what’s
              mathematically true.
            </p>
          </div>
          <Link href="/demo" className="export-button">
            Try the whole loop <ArrowUpRight size={15} />
          </Link>
        </div>
        <BrainPanel />
        <div className="mission-explanation">
          <span className="eyebrow">
            MISSION ENGINE · {mission.skill.title}
          </span>
          <p>{mission.reason}</p>
        </div>
        <div className="lab-grid">
          <section className="architecture">
            <div className="panel-kicker">
              <Code2 size={15} /> THE LEARNING ENGINE
            </div>
            {layers.map(([title, description], i) => (
              <div key={title}>
                <div className={`architecture-node layer-${i}`}>
                  <span>{String(i + 1).padStart(2, "0")}</span>
                  <div>
                    <h3>{title}</h3>
                    <p>{description}</p>
                  </div>
                  {i === 1 && <ShieldCheck size={21} />}
                </div>
                {i < layers.length - 1 && (
                  <ArrowDown className="architecture-arrow" size={15} />
                )}
              </div>
            ))}
          </section>
          <div className="lab-right">
            <section className="evaluation-panel">
              <div className="panel-kicker">
                <FlaskConical size={15} /> MEASURED, NOT MADE UP
              </div>
              <h2>Reliability, under a microscope.</h2>
              <p>
                Generated by the local evaluation harness. Synthetic learners
                only.
              </p>
              <div className="metric-grid">
                <Metric
                  value={
                    metrics.status === "pending" ? "—" : String(metrics.kernels)
                  }
                  label="Exact math kernels"
                />
                <Metric
                  value={
                    metrics.status === "pending"
                      ? "—"
                      : String(metrics.mathFailures)
                  }
                  label="Math validation failures"
                />
                <Metric
                  value={
                    metrics.schemaCases
                      ? `${metrics.schemaPassed}/${metrics.schemaCases}`
                      : "—"
                  }
                  label="Schema contract checks"
                />
                <Metric
                  value={
                    metrics.learnerTraces
                      ? `${metrics.tracesPassed}/${metrics.learnerTraces}`
                      : "—"
                  }
                  label="Synthetic learner traces"
                />
                <Metric
                  value={
                    metrics.fallbackCases
                      ? `${metrics.fallbackPassed}/${metrics.fallbackCases}`
                      : "—"
                  }
                  label="Local explanation fixtures"
                />
                <Metric
                  value={`${localMetrics.passed}/${localMetrics.cases}`}
                  label="Live Qwen fixture agreement"
                />
              </div>
              <p className="measurement-note">
                Qwen3-8B · {localMetrics.liveRequests} live requests ·{" "}
                {localMetrics.meanLatencyMs} ms mean ·{" "}
                {localMetrics.generatedAt}
              </p>
              <span className="evaluation-source">
                {metrics.generatedAt
                  ? `Last run: ${metrics.generatedAt}`
                  : "Evaluation results will appear after the harness runs."}
              </span>
            </section>
            <section className="runtime-panel">
              <div className="panel-kicker">
                <Activity size={15} /> THIS SESSION, RIGHT NOW
              </div>
              <div className="runtime-row">
                <span>Explanation evaluations</span>
                <b>{aiEvents.length}</b>
              </div>
              <div className="runtime-row">
                <span>Fallback activations</span>
                <b>{fallback}</b>
              </div>
              <div className="runtime-row">
                <span>Mean evaluation round trip</span>
                <b>{latency === null ? "No calls yet" : `${latency} ms`}</b>
              </div>
              <p>
                Fallback results are labelled in the evidence stream. No
                simulated AI metrics.
              </p>
            </section>
          </div>
        </div>
        <section className="guardrails">
          <h2>Clear boundaries make room for better learning.</h2>
          <div>
            <p>
              <Check size={17} /> AI evaluates reasoning, never writing style.
            </p>
            <p>
              <Check size={17} /> Exact math stays in pure, tested functions.
            </p>
            <p>
              <Check size={17} /> Procedural repetition cannot bypass mastery
              gates.
            </p>
            <p>
              <Check size={17} /> Audio is transient. Identity isn’t needed.
            </p>
          </div>
        </section>
        <div className="lab-eval-note">
          <strong>What these results establish</strong>
          <p>
            Math and policy tests verify implementation invariants. Local
            explanation fixtures test a conservative authored rubric, not live
            model quality or educational efficacy. Qwen runs locally without a
            key. The separate Qwen development evaluation uses synthetic
            explanations; it is a small development check, not a population
            accuracy estimate. Mastery scores are transparent heuristics
            awaiting classroom validation.
          </p>
        </div>
      </div>
      <Footer />
    </main>
  );
}
function Metric({ value, label }: { value: string; label: string }) {
  return (
    <div>
      <strong>{value}</strong>
      <span>{label}</span>
    </div>
  );
}
